source 'http://rubygems.org'

ruby '2.1.7'

gem 'rails', '4.2.0'
gem 'rails-api'
gem 'pg'
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]
gem 'ruleby', '~> 0.8'
gem 'jbuilder', '~> 1.2'

gem 'devise_token_auth'
gem 'omniauth-github'
gem 'omniauth-facebook'
gem 'omniauth-google-oauth2'
gem "cancan"
gem 'seed_dump'
